#!/bin/bash
set -euo pipefail

SDK=${ANDROID_SDK:-/opt/AndroidStudio/Android/sdk}
BUILD_TOOLS_VERSION=${BUILD_TOOLS_VERSION:-36.1.0}
PLATFORM_VERSION=${PLATFORM_VERSION:-android-35}
BUILD_TOOLS=$SDK/build-tools/$BUILD_TOOLS_VERSION
PLATFORM=$SDK/platforms/$PLATFORM_VERSION
PROJECT=$(cd "$(dirname "$0")" && pwd)

AAPT2=$BUILD_TOOLS/aapt2
D8=$BUILD_TOOLS/d8
APKSIGNER=$BUILD_TOOLS/apksigner
ZIPALIGN=$BUILD_TOOLS/zipalign
ANDROID_JAR=$PLATFORM/android.jar

SRC=$PROJECT/app/src/main
RES=$SRC/res
SRC_ASSETS=$SRC/assets
MANIFEST=$SRC/AndroidManifest.xml
JAVA_SRC=$SRC/java
BUILD=$PROJECT/build
OUTPUT_DIR=$BUILD/apk

COUNTER_FILE=$PROJECT/build_counter.txt
BUILD_NUM=$(cat "$COUNTER_FILE" 2>/dev/null || echo 1)
VERSION_NAME=${VERSION_NAME:-3.0.31}

# --- osmdroid (OpenStreetMap library for geofence editing) ---
# The AAR is fetched once from Maven Central into libs/ and reused offline.
OSMDROID_VERSION=6.1.18
OSMDROID_AAR=$PROJECT/libs/osmdroid-android-$OSMDROID_VERSION.aar
OSMDROID_URL=https://repo1.maven.org/maven2/org/osmdroid/osmdroid-android/$OSMDROID_VERSION/osmdroid-android-$OSMDROID_VERSION.aar
OSMDROID_DIR=$BUILD/osmdroid-$OSMDROID_VERSION

prepare_osmdroid() {
    if [[ ! -f "$OSMDROID_AAR" ]]; then
        mkdir -p "$(dirname "$OSMDROID_AAR")"
        echo "=== Downloading osmdroid $OSMDROID_VERSION from Maven Central ==="
        curl -fL --retry 3 -o "$OSMDROID_AAR" "$OSMDROID_URL"
    fi
    if [[ ! -f "$OSMDROID_DIR/classes.jar" ]]; then
        rm -rf "$OSMDROID_DIR"
        mkdir -p "$OSMDROID_DIR"
        unzip -q -o "$OSMDROID_AAR" -d "$OSMDROID_DIR"
    fi
}

# --- androidx.core (FileProvider for the update installer) ---
# Reused from the local Gradle cache; same artifact the Gradle build resolves.
ANDROIDX_CORE_DIR=$BUILD/androidx-core

prepare_androidx_core() {
    if [[ -f "$ANDROIDX_CORE_DIR/classes.jar" ]]; then return; fi
    local aar
    aar=$(find ~/.gradle/caches/modules-2/files-2.1/androidx.core/core -name "core-*.aar" 2>/dev/null | sort | tail -1)
    if [[ -z "$aar" ]]; then
        echo "ERROR: androidx.core AAR not found in Gradle cache (run ./gradlew assembleRelease once)" >&2
        exit 1
    fi
    rm -rf "$ANDROIDX_CORE_DIR"
    mkdir -p "$ANDROIDX_CORE_DIR"
    unzip -q -o "$aar" -d "$ANDROIDX_CORE_DIR"
}

# Generate org/osmdroid/library/R.java whose fields alias the app R class
# (aapt2 links app+lib resources into a single com.car2hass.R table).
gen_osmdroid_r() {
    local rtxt=$1
    local out=$2
    mkdir -p "$(dirname "$out")"
    {
        echo "package org.osmdroid.library;"
        echo "/** Auto-generated by build_apk.sh: aliases to merged app resources. */"
        echo "public final class R {"
        for type in drawable id layout string; do
            echo "    public static final class $type {"
            grep "^int $type " "$rtxt" | awk -v t="$type" \
                '{printf "        public static final int %s = com.car2hass.R.%s.%s;\n", $3, t, $3}'
            echo "    }"
        done
        echo "}"
    } > "$out"
}

# Determine keystore credentials
DEV_KEYSTORE=$PROJECT/.keys/dev-release.jks
DEV_ALIAS=devkey
DEV_PASS=devpass

if [[ -n "${KEYSTORE_PASS:-}" && -n "${KEY_ALIAS:-}" && -n "${KEY_PASS:-}" && -n "${KEYSTORE_FILE:-}" ]]; then
    KEYSTORE=$KEYSTORE_FILE
    KEY_ALIAS_VAL=$KEY_ALIAS
    KEYSTORE_PASS_VAL=$KEYSTORE_PASS
    KEY_PASS_VAL=$KEY_PASS
    echo "=== Using release keystore from environment variables ==="
elif [[ -f "$DEV_KEYSTORE" ]]; then
    KEYSTORE=$DEV_KEYSTORE
    KEY_ALIAS_VAL=$DEV_ALIAS
    KEYSTORE_PASS_VAL=$DEV_PASS
    KEY_PASS_VAL=$DEV_PASS
    echo "=== WARNING: Using development keystore ($DEV_KEYSTORE) ==="
    echo "=== For release builds set KEYSTORE_FILE, KEYSTORE_PASS, KEY_ALIAS, KEY_PASS environment variables ==="
else
    echo "ERROR: No signing credentials configured." >&2
    echo "Either set KEYSTORE_FILE, KEYSTORE_PASS, KEY_ALIAS, KEY_PASS environment variables," >&2
    echo "or generate a dev keystore with: mkdir -p $PROJECT/.keys && keytool -genkey -keystore $DEV_KEYSTORE -alias $DEV_ALIAS -keyalg RSA -keysize 2048 -validity 10000 -storepass $DEV_PASS -keypass $DEV_PASS -dname 'CN=Car2Hass Dev'" >&2
    exit 1
fi

# Verify Java version (17+)
JAVA_VERSION=$(java -version 2>&1 | head -1 | sed -e 's/.*version "\([0-9.]*\).*/\1/')
if [[ "$JAVA_VERSION" =~ ^1\. ]]; then
    JAVA_MAJOR=${JAVA_VERSION%%.*}
else
    JAVA_MAJOR=${JAVA_VERSION%%.*}
fi
if [[ "$JAVA_MAJOR" -lt 17 ]]; then
    echo "ERROR: Java 17+ is required for Android API 35. Current: $JAVA_VERSION" >&2
    exit 1
fi

build_variant() {
    local variant=$1
    local build_debug=$2
    local apk_final=$3

    local variant_build=$BUILD/$variant
    local gen=$variant_build/gen
    local classes=$variant_build/classes
    local assets=$variant_build/assets
    local resources_zip=$variant_build/resources.zip
    local apk_unsigned=$variant_build/Car2Hass-unsigned.apk

    echo ""
    echo "==========================================="
    echo "=== Building $variant variant (DEBUG=$build_debug) ==="
    echo "==========================================="

    rm -rf "$variant_build"
    mkdir -p "$gen" "$classes" "$assets" "$OUTPUT_DIR"

    # Prepare assets for this variant
    echo "=== Preparing assets ($variant) ==="
    if [[ -d "$SRC_ASSETS" ]]; then
        cp -r "$SRC_ASSETS"/* "$assets/"
    fi
    if [[ "$variant" == "test" ]]; then
        if [[ -f "$PROJECT/test/config.json" ]]; then
            cp "$PROJECT/test/config.json" "$assets/config.json"
            echo "=== Replaced assets/config.json with test/config.json ==="
        else
            echo "WARNING: test/config.json not found, using template assets/config.json" >&2
        fi
    fi

    # Generate BuildConfig.java
    echo "=== Generating BuildConfig (DEBUG=$build_debug) ==="
    mkdir -p "$gen/com/car2hass"
    cat > "$gen/com/car2hass/BuildConfig.java" <<EOF
package com.car2hass;

public final class BuildConfig {
    public static final boolean DEBUG = $build_debug;
    public static final String VERSION_NAME = "$VERSION_NAME";
    public static final int VERSION_CODE = $BUILD_NUM;
}
EOF

    echo "=== Step 1: Compile resources ($variant) ==="
    $AAPT2 compile --dir "$RES" -o "$resources_zip"

    echo "=== Step 1b: Compile osmdroid resources ($variant) ==="
    local osmdroid_res_zip=$variant_build/osmdroid-res.zip
    $AAPT2 compile --dir "$OSMDROID_DIR/res" -o "$osmdroid_res_zip"

    echo "=== Step 2: Link resources ($variant, build #$BUILD_NUM) ==="
    $AAPT2 link \
        -o "$apk_unsigned" \
        -I "$ANDROID_JAR" \
        --manifest "$MANIFEST" \
        --version-code "$BUILD_NUM" \
        --version-name "$VERSION_NAME" \
        -R "$resources_zip" \
        -R "$osmdroid_res_zip" \
        --java "$gen" \
        --auto-add-overlay \
        -A "$assets"

    echo "=== Step 2b: Generate osmdroid R.java aliases ($variant) ==="
    gen_osmdroid_r "$OSMDROID_DIR/R.txt" "$gen/org/osmdroid/library/R.java"

    echo "=== Step 3: Compile Java sources ($variant) ==="
    local java_files=(
        "$gen/com/car2hass/R.java"
        "$gen/com/car2hass/BuildConfig.java"
        "$gen/org/osmdroid/library/R.java"
        $(find "$JAVA_SRC" -name '*.java')
    )
        javac -d "$classes" \
        -classpath "$ANDROID_JAR:$OSMDROID_DIR/classes.jar:$ANDROIDX_CORE_DIR/classes.jar" \
        -source 17 -target 17 \
        -sourcepath "$JAVA_SRC" \
        "${java_files[@]}"

    echo "=== Step 4: Convert to DEX ($variant) ==="
    $D8 --release --output "$variant_build" \
        --lib "$ANDROID_JAR" \
        "$OSMDROID_DIR/classes.jar" \
        "$ANDROIDX_CORE_DIR/classes.jar" \
        $(find "$classes" -name '*.class')

    echo "=== Step 5: Add DEX to APK ($variant) ==="
    cd "$variant_build"
    for f in classes*.dex; do
        if [ -f "$f" ]; then
            zip -q "$apk_unsigned" "$f"
        fi
    done
    cd "$PROJECT"

    echo "=== Step 6: Align APK ($variant) ==="
    $ZIPALIGN -f -p 4 "$apk_unsigned" "${apk_unsigned}.aligned"
    mv "${apk_unsigned}.aligned" "$apk_unsigned"

    echo "=== Step 7: Sign APK ($variant) ==="
    $APKSIGNER sign --ks "$KEYSTORE" \
        --ks-pass "pass:$KEYSTORE_PASS_VAL" \
        --ks-key-alias "$KEY_ALIAS_VAL" \
        --key-pass "pass:$KEY_PASS_VAL" \
        --out "$apk_final" "$apk_unsigned"

    echo "=== Step 8: Verify alignment and signature ($variant) ==="
    $ZIPALIGN -c -v 4 "$apk_final" 2>/dev/null || echo "WARNING: alignment verification failed"
    $APKSIGNER verify "$apk_final" || echo "WARNING: signature verification failed"

    echo ""
    echo "=== $variant APK built: $apk_final ==="
    ls -lh "$apk_final"
}

echo "=== Build project: $PROJECT (build #$BUILD_NUM, version $VERSION_NAME, Java $JAVA_VERSION) ==="
echo "=== Both release and test APKs will be built into $OUTPUT_DIR ==="

# Clean intermediate files from previous single-variant builds but keep output dir
rm -rf "$BUILD/release" "$BUILD/test" "$BUILD/gen" "$BUILD/classes" "$BUILD/assets" "$BUILD/resources.zip" \
       "$BUILD/Car2Hass-unsigned.apk" "${BUILD}/Car2Hass-unsigned.apk.aligned"
mkdir -p "$OUTPUT_DIR"

prepare_osmdroid
prepare_androidx_core

# Build release and test variants into the same output directory, versioned
build_variant "release" "false" "$OUTPUT_DIR/Car2Hass_v$VERSION_NAME.apk"
build_variant "test" "true" "$OUTPUT_DIR/Car2Hass_v${VERSION_NAME}_test.apk"

# --- Prune old APK versions: keep the current one + the 3 previous ones ---
# and drop legacy non-versioned files. Version-sorted so 3.0.9 < 3.0.10.
KEEP=4
cd "$OUTPUT_DIR" || exit 1
KEEP_LIST=$(ls Car2Hass_v*.apk 2>/dev/null \
    | sed -E 's/^Car2Hass_v([0-9][0-9.]*)(_test)?\.apk$/\1/' \
    | sort -Vu -r | head -n "$KEEP" | tr '\n' ' ')
for f in Car2Hass_v*.apk; do
    [ -e "$f" ] || continue
    v=$(echo "$f" | sed -E 's/^Car2Hass_v([0-9][0-9.]*)(_test)?\.apk$/\1/')
    if ! echo "$KEEP_LIST" | grep -qw "$v"; then
        rm -f "$f"
    fi
done
rm -f Car2Hass.apk Car2Hass-test.apk
cd "$PROJECT"

# --- Stage the release into the site folder (docs/cartelemetry/) ---
# Copies the APK, packs the integration zip and regenerates the API spec
# so the site folder is ready to publish after every release build.
SITE_DIR=$PROJECT/../docs/cartelemetry
stage_site_release() {
    if [[ ! -d "$SITE_DIR" ]]; then
        echo "NOTE: site dir $SITE_DIR not found — skipping site staging"
        return 0
    fi
    echo "=== Staging release into site folder ==="

    # APK under its published name; drop the previous release file
    local apk_name="car2hass-v$VERSION_NAME.apk"
    rm -f "$SITE_DIR"/car2hass-v*.apk
    cp "$OUTPUT_DIR/Car2Hass_v$VERSION_NAME.apk" "$SITE_DIR/$apk_name"

    # Integration zip from custom_components (no caches inside)
    local zip_name="cartelemetry-v$VERSION_NAME.zip"
    rm -f "$SITE_DIR"/cartelemetry-v*.zip
    (cd "$PROJECT/../custom_components" && \
        zip -qr "$SITE_DIR/$zip_name" cartelemetry -x "*/__pycache__/*" "*/.*")

    # Machine-readable API spec for the site endpoint
    python3 "$PROJECT/../scripts/signals_tool.py" gen-spec >/dev/null || \
        echo "WARN: gen-spec failed — spec.json not refreshed"

    echo "Staged: $apk_name, $zip_name, api/spec/spec.json -> $SITE_DIR"
}
stage_site_release

echo $((BUILD_NUM + 1)) > "$COUNTER_FILE"

echo ""
echo "==========================================="
echo "All APKs built successfully (build #$BUILD_NUM, version $VERSION_NAME):"
ls -lh "$OUTPUT_DIR"/*.apk
echo "==========================================="
