DOMAIN = "cartelemetry"

CONF_CAR_NAME = "car_name"

INTEGRATION_VERSION = "3.0.22"

# Sensor considered offline after this many seconds without updates.
ONLINE_OFFLINE_SECONDS = 60

# Numeric signals and their configurations
# Keys must match the stable keys generated by the Android app.
NUMERIC_SENSORS = {
    "speed": {
        "name": "Speed (km/h)",
        "unit": "km/h",
        "icon": "mdi:speedometer",
        "device_class": "speed",
        "state_class": "measurement",
    },
    "range": {
        "name": "Range / mileage",
        "unit": "km",
        "icon": "mdi:map-marker-distance",
        "state_class": "measurement",
    },
    "engine_rpm": {
        "name": "Engine RPM",
        "unit": "rpm",
        "icon": "mdi:engine",
        "state_class": "measurement",
    },
    "brake_pedal": {
        "name": "Brake pedal depth",
        "unit": "%",
        "icon": "mdi:car-brake-hold",
        "state_class": "measurement",
    },
    "accel_pedal": {
        "name": "Accelerator pedal depth",
        "unit": "%",
        "icon": "mdi:car",
        "state_class": "measurement",
    },
    "front_motor_rpm": {
        "name": "Front motor RPM",
        "unit": "rpm",
        "icon": "mdi:engine",
        "state_class": "measurement",
    },
    "rear_motor_rpm": {
        "name": "Rear motor RPM",
        "unit": "rpm",
        "icon": "mdi:engine",
        "state_class": "measurement",
    },
    "engine_power": {
        "name": "Engine power",
        "unit": "kW",
        "icon": "mdi:lightning-bolt",
        "state_class": "measurement",
    },
    "front_motor_torque": {
        "name": "Front motor torque",
        "unit": "Nm",
        "icon": "mdi:lightning-bolt",
        "state_class": "measurement",
    },
    "energy_per_100km": {
        "name": "Energy per 100 km",
        "unit": "kWh",
        "icon": "mdi:lightning-bolt",
        "state_class": "measurement",
    },
    "battery_temp_max": {
        "name": "Max battery temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "battery_temp_avg": {
        "name": "Avg battery temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "battery_temp_min": {
        "name": "Min battery temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "cell_voltage_max": {
        "name": "Max cell voltage",
        "unit": "V",
        "icon": "mdi:battery",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    "cell_voltage_min": {
        "name": "Min cell voltage",
        "unit": "V",
        "icon": "mdi:battery",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    "last_wiper_time": {
        "name": "Last wiper time",
        "unit": "s",
        "icon": "mdi:wiper",
    },
    "cabin_temp": {
        "name": "Cabin temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "outside_temp": {
        "name": "Outside temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "ac_set_temp": {
        "name": "Driver A/C set temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "battery_capacity": {
        "name": "Battery capacity",
        "unit": "kWh",
        "icon": "mdi:battery",
        "state_class": "measurement",
    },
    "steering_angle": {
        "name": "Steering wheel angle",
        "unit": "°",
        "icon": "mdi:steering",
        "state_class": "measurement",
    },
    "steering_rate": {
        "name": "Steering wheel rate",
        "unit": "°/s",
        "icon": "mdi:steering",
        "state_class": "measurement",
    },
    "total_energy": {
        "name": "Total energy consumption",
        "unit": "kWh",
        "icon": "mdi:counter",
        "state_class": "total",
    },
    "battery_charge": {
        "name": "Battery charge (%)",
        "unit": "%",
        "icon": "mdi:battery",
        "device_class": "battery",
        "state_class": "measurement",
    },
    "fuel_level": {
        "name": "Fuel level (%)",
        "unit": "%",
        "icon": "mdi:gas-station",
        "state_class": "measurement",
    },
    "total_fuel": {
        "name": "Total fuel consumption",
        "unit": "L",
        "icon": "mdi:gas-station",
        "state_class": "total_increasing",
    },
    "lane_curvature": {
        "name": "Lane curvature",
        "unit": "",
        "icon": "mdi:road-variant",
        "state_class": "measurement",
    },
    "right_lane_distance": {
        "name": "Right lane distance",
        "unit": "m",
        "icon": "mdi:road-variant",
        "state_class": "measurement",
    },
    "left_lane_distance": {
        "name": "Left lane distance",
        "unit": "m",
        "icon": "mdi:road-variant",
        "state_class": "measurement",
    },
    "battery_voltage": {
        "name": "12V battery voltage",
        "unit": "V",
        "icon": "mdi:car",
        "device_class": "voltage",
        "state_class": "measurement",
    },
    "radar_fl": {
        "name": "Radar front-left",
        "unit": "m",
        "icon": "mdi:radar",
        "state_class": "measurement",
    },
    "radar_fr": {
        "name": "Radar front-right",
        "unit": "m",
        "icon": "mdi:radar",
        "state_class": "measurement",
    },
    "radar_rl": {
        "name": "Radar rear-left",
        "unit": "m",
        "icon": "mdi:radar",
        "state_class": "measurement",
    },
    "radar_rr": {
        "name": "Radar rear-right",
        "unit": "m",
        "icon": "mdi:radar",
        "state_class": "measurement",
    },
    "radar_left": {
        "name": "Radar left",
        "unit": "m",
        "icon": "mdi:radar",
        "state_class": "measurement",
    },
    "radar_flc": {
        "name": "Radar front-left-center",
        "unit": "m",
        "icon": "mdi:radar",
        "state_class": "measurement",
    },
    "radar_frc": {
        "name": "Radar front-right-center",
        "unit": "m",
        "icon": "mdi:radar",
        "state_class": "measurement",
    },
    "radar_rc": {
        "name": "Radar rear-center",
        "unit": "m",
        "icon": "mdi:radar",
        "state_class": "measurement",
    },
    "front_wiper_speed": {
        "name": "Front wiper speed",
        "unit": "",
        "icon": "mdi:wiper",
        "state_class": "measurement",
    },
    "wiper_mode": {
        "name": "Wiper mode",
        "unit": "",
        "icon": "mdi:wiper",
    },
    "cruise_switch": {
        "name": "Cruise switch",
        "unit": "",
        "icon": "mdi:cruise-control",
    },
    "distance_to_car_ahead": {
        "name": "Distance to car ahead",
        "unit": "m",
        "icon": "mdi:car",
        "state_class": "measurement",
    },
    "tyre_pressure_fl": {
        "name": "Tyre pressure FL",
        "unit": "kPa",
        "icon": "mdi:car",
        "device_class": "pressure",
        "state_class": "measurement",
    },
    "tyre_pressure_fr": {
        "name": "Tyre pressure FR",
        "unit": "kPa",
        "icon": "mdi:car",
        "device_class": "pressure",
        "state_class": "measurement",
    },
    "tyre_pressure_rl": {
        "name": "Tyre pressure RL",
        "unit": "kPa",
        "icon": "mdi:car",
        "device_class": "pressure",
        "state_class": "measurement",
    },
    "tyre_pressure_rr": {
        "name": "Tyre pressure RR",
        "unit": "kPa",
        "icon": "mdi:car",
        "device_class": "pressure",
        "state_class": "measurement",
    },
    "window_fl": {
        "name": "Window FL open (%)",
        "unit": "%",
        "icon": "mdi:car-door",
        "state_class": "measurement",
    },
    "window_fr": {
        "name": "Window FR open (%)",
        "unit": "%",
        "icon": "mdi:car-door",
        "state_class": "measurement",
    },
    "window_rl": {
        "name": "Window RL open (%)",
        "unit": "%",
        "icon": "mdi:car-door",
        "state_class": "measurement",
    },
    "window_rr": {
        "name": "Window RR open (%)",
        "unit": "%",
        "icon": "mdi:car-door",
        "state_class": "measurement",
    },
    "sunroof": {
        "name": "Sunroof open (%)",
        "unit": "%",
        "icon": "mdi:car-convertible",
        "state_class": "measurement",
    },
    "sunshade": {
        "name": "Sunshade open (%)",
        "unit": "%",
        "icon": "mdi:car-convertible",
        "state_class": "measurement",
    },
    "month": {
        "name": "Month",
        "unit": "",
        "icon": "mdi:calendar",
    },
    "day": {
        "name": "Day",
        "unit": "",
        "icon": "mdi:calendar",
    },
    "hour": {
        "name": "Hour",
        "unit": "",
        "icon": "mdi:clock",
    },
    "minute": {
        "name": "Minute",
        "unit": "",
        "icon": "mdi:clock",
    },
    "fan_speed": {
        "name": "Fan speed level",
        "unit": "",
        "icon": "mdi:fan",
        "state_class": "measurement",
    },
    "engine_coolant_temp": {
        "name": "Engine coolant temp",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "device_class": "temperature",
        "state_class": "measurement",
    },
    "slope": {
        "name": "Slope / grade",
        "unit": "°",
        "icon": "mdi:hill",
        "state_class": "measurement",
    },
    "rain_amount": {
        "name": "Rain amount",
        "unit": "mm",
        "icon": "mdi:weather-rainy",
        "device_class": "precipitation",
        "state_class": "measurement",
    },
    "second": {
        "name": "Second",
        "unit": "",
        "icon": "mdi:clock",
    },
    "soc": {
        "name": "Battery SOC (%)",
        "unit": "%",
        "icon": "mdi:battery",
        "device_class": "battery",
        "state_class": "measurement",
    },
    "bluetooth_signal": {
        "name": "Bluetooth signal",
        "unit": "dBm",
        "icon": "mdi:bluetooth-audio",
        "state_class": "measurement",
    },
    "sway_magnitude": {
        "name": "Sway magnitude",
        "unit": "",
        "icon": "mdi:car-swing",
        "state_class": "measurement",
    },
    "vibration_magnitude": {
        "name": "Vibration magnitude",
        "unit": "",
        "icon": "mdi:vibrate",
        "state_class": "measurement",
    },
    "screen_width": {
        "name": "Screen width",
        "unit": "px",
        "icon": "mdi:monitor",
    },
    "screen_height": {
        "name": "Screen height",
        "unit": "px",
        "icon": "mdi:monitor",
    },
    "media_volume": {
        "name": "Media volume",
        "unit": "%",
        "icon": "mdi:volume-high",
        "state_class": "measurement",
    },
    "navigation_volume": {
        "name": "Navigation volume",
        "unit": "%",
        "icon": "mdi:volume-high",
        "state_class": "measurement",
    },
    "ai_person_confidence": {
        "name": "AI person confidence",
        "unit": "%",
        "icon": "mdi:face-recognition",
        "state_class": "measurement",
    },
    "ai_vehicle_confidence": {
        "name": "AI vehicle confidence",
        "unit": "%",
        "icon": "mdi:car",
        "state_class": "measurement",
    },
    "last_sentry_trigger_time": {
        "name": "Last sentry trigger time",
        "unit": "s",
        "icon": "mdi:shield-car",
    },
    "last_clip_start_time": {
        "name": "Last clip start time",
        "unit": "s",
        "icon": "mdi:video",
    },
    "last_clip_end_time": {
        "name": "Last clip end time",
        "unit": "s",
        "icon": "mdi:video",
    },
    "wifi_rssi": {
        "name": "WiFi RSSI",
        "unit": "dBm",
        "icon": "mdi:wifi",
        "device_class": "signal_strength",
        "state_class": "measurement",
    },
    "location_lat": {
        "name": "GPS latitude",
        "unit": "deg",
        "icon": "mdi:latitude",
        "state_class": "measurement",
    },
    "location_lon": {
        "name": "GPS longitude",
        "unit": "deg",
        "icon": "mdi:longitude",
        "state_class": "measurement",
    },
    "location_speed": {
        "name": "GPS speed",
        "unit": "km/h",
        "icon": "mdi:speedometer",
        "device_class": "speed",
        "state_class": "measurement",
    },
    "location_bearing": {
        "name": "GPS bearing",
        "unit": "deg",
        "icon": "mdi:compass",
        "state_class": "measurement",
    },
    "location_altitude": {
        "name": "GPS altitude",
        "unit": "m",
        "icon": "mdi:image-filter-hdr",
        "device_class": "distance",
        "state_class": "measurement",
    },
    "location_accuracy": {
        "name": "GPS accuracy",
        "unit": "m",
        "icon": "mdi:crosshairs-gps",
        "device_class": "distance",
        "state_class": "measurement",
    },
    "device_battery": {
        "name": "Head unit battery level",
        "unit": "%",
        "icon": "mdi:battery",
        "device_class": "battery",
        "state_class": "measurement",
    },
    "engine_load": {
        "name": "Engine load",
        "unit": "%",
        "icon": "mdi:gauge",
        "state_class": "measurement",
    },
    "intake_air_temp": {
        "name": "Intake air temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "state_class": "measurement",
    },
    "maf": {
        "name": "MAF air flow",
        "unit": "g/s",
        "icon": "mdi:air-filter",
        "state_class": "measurement",
    },
    "ambient_temp": {
        "name": "Ambient temperature",
        "unit": "°C",
        "icon": "mdi:thermometer",
        "state_class": "measurement",
    },
    "engine_oil_temp": {
        "name": "Engine oil temperature",
        "unit": "°C",
        "icon": "mdi:oil-temperature",
        "state_class": "measurement",
    },
    "fuel_rate": {
        "name": "Fuel consumption rate",
        "unit": "L/h",
        "icon": "mdi:gas-station",
        "state_class": "measurement",
    },
    "charge_rate": {
        "name": "Charge rate",
        "unit": "kW",
        "icon": "mdi:lightning-bolt",
        "state_class": "measurement",
    },
}

# Enum/text signals — string-valued signals from the vehicle
ENUM_SENSORS = {
    "gear": {
        "name": "Gear",
        "icon": "mdi:car-shift-pattern",
    },
    "charge_gun_state": {
        "name": "Charge gun plug state",
        "icon": "mdi:ev-plug",
    },
    "weather": {
        "name": "Weather",
        "icon": "mdi:weather-partly-cloudy",
    },
    "temp_unit": {
        "name": "Temperature unit",
        "icon": "mdi:thermometer",
    },
    "powertrain_mode": {
        "name": "Powertrain work mode",
        "icon": "mdi:car-engine",
    },
    "drive_mode": {
        "name": "Drive mode",
        "icon": "mdi:car-settings",
    },
    "ac_airflow_mode": {
        "name": "A/C airflow mode",
        "icon": "mdi:fan",
    },
    "acc_cruise_state": {
        "name": "ACC cruise state",
        "icon": "mdi:cruise-control",
    },
    "ui_config_version": {
        "name": "UI config version",
        "icon": "mdi:monitor-dashboard",
    },
    "sentry_state": {
        "name": "Sentry state",
        "icon": "mdi:shield-car",
    },
    "parked_recording_switch": {
        "name": "Parked-recording switch",
        "icon": "mdi:video-switch",
    },
    "parked_sentry_alarm": {
        "name": "Parked sentry alarm",
        "icon": "mdi:shield-alert",
    },
    "lead_car_start_state": {
        "name": "Lead-car start state",
        "icon": "mdi:car",
    },
    "app_version": {
        "name": "App version",
        "icon": "mdi:information-outline",
    },
    "wifi_ssid": {
        "name": "WiFi SSID",
        "icon": "mdi:wifi",
    },
    "wifi_bssid": {
        "name": "WiFi BSSID",
        "icon": "mdi:wifi",
    },
    "location_provider": {
        "name": "Location provider",
        "icon": "mdi:car",
    },
    "driver_seat_heat": {
        "name": "Driver seat heating",
        "icon": "mdi:car-seat-heater",
    },
    "passenger_seat_heat": {
        "name": "Passenger seat heating",
        "icon": "mdi:car-seat-heater",
    },
    "driver_seat_vent": {
        "name": "Driver seat ventilation",
        "icon": "mdi:fan",
    },
    "passenger_seat_vent": {
        "name": "Passenger seat ventilation",
        "icon": "mdi:fan",
    },
    "rear_left_seat_heat": {
        "name": "Rear-left seat heating",
        "icon": "mdi:car-seat-heater",
    },
    "rear_right_seat_heat": {
        "name": "Rear-right seat heating",
        "icon": "mdi:car-seat-heater",
    },
    "steering_wheel_heat": {
        "name": "Steering wheel heating",
        "icon": "mdi:car-defrost-rear",
    },
    "rear_defrost": {
        "name": "Rear window defrost",
        "icon": "mdi:car-defrost-rear",
    },
    "mirror_fold": {
        "name": "Rear mirror fold",
        "icon": "mdi:car-side",
    },
}

# Binary sensor signals — mapped from enum values
# Keys must match the stable keys generated by the Android app.
BINARY_SENSORS = {
    "power_state": {
        "name": "Power state",
        "device_class": "power",
    },
    "driver_seatbelt": {
        "name": "Driver seatbelt state",
        "device_class": "safety",
    },
    "remote_lock_state": {
        "name": "Remote lock state",
        "device_class": "lock",
    },
    "charging_state": {
        "name": "Charging state",
        "device_class": "battery_charging",
    },
    "left_turn": {
        "name": "Left turn signal",
        "device_class": "light",
    },
    "right_turn": {
        "name": "Right turn signal",
        "device_class": "light",
    },
    "driver_door_lock": {
        "name": "Driver door lock",
        "device_class": "lock",
    },
    "passenger_seatbelt_warning": {
        "name": "Passenger seatbelt warning",
        "device_class": "safety",
    },
    "seatbelt_2nd_left": {
        "name": "2nd row left seatbelt",
        "device_class": "safety",
    },
    "seatbelt_2nd_right": {
        "name": "2nd row right seatbelt",
        "device_class": "safety",
    },
    "seatbelt_2nd_center": {
        "name": "2nd row center seatbelt",
        "device_class": "safety",
    },
    "ac_state": {
        "name": "A/C state",
        "device_class": "cold",
    },
    "ac_recirculation": {
        "name": "A/C recirculation",
        "device_class": "cold",
    },
    "driver_door": {
        "name": "Driver door",
        "device_class": "door",
    },
    "passenger_door": {
        "name": "Passenger door",
        "device_class": "door",
    },
    "rear_left_door": {
        "name": "Rear-left door",
        "device_class": "door",
    },
    "rear_right_door": {
        "name": "Rear-right door",
        "device_class": "door",
    },
    "bonnet": {
        "name": "Bonnet",
        "device_class": "door",
    },
    "trunk": {
        "name": "Trunk",
        "device_class": "door",
    },
    "fuel_charge_flap": {
        "name": "Fuel/charge flap",
        "device_class": "door",
    },
    "auto_hold": {
        "name": "Auto hold",
        "device_class": "safety",
    },
    "rear_left_approach_warning": {
        "name": "Rear-left approach warning",
        "device_class": "safety",
    },
    "rear_right_approach_warning": {
        "name": "Rear-right approach warning",
        "device_class": "safety",
    },
    "lane_keep_state": {
        "name": "Lane keep state",
        "device_class": "safety",
    },
    "rear_left_door_lock": {
        "name": "Rear-left door lock",
        "device_class": "lock",
    },
    "passenger_door_lock": {
        "name": "Passenger door lock",
        "device_class": "lock",
    },
    "rear_right_door_lock": {
        "name": "Rear-right door lock",
        "device_class": "lock",
    },
    "trunk_lock": {
        "name": "Trunk lock",
        "device_class": "lock",
    },
    "rear_left_child_lock": {
        "name": "Rear-left child lock",
        "device_class": "lock",
    },
    "rear_right_child_lock": {
        "name": "Rear-right child lock",
        "device_class": "lock",
    },
    "sidelights": {
        "name": "Sidelights",
        "device_class": "light",
    },
    "low_beam": {
        "name": "Low beam",
        "device_class": "light",
    },
    "high_beam": {
        "name": "High beam",
        "device_class": "light",
    },
    "front_fog": {
        "name": "Front fog",
        "device_class": "light",
    },
    "rear_fog": {
        "name": "Rear fog",
        "device_class": "light",
    },
    "footwell_light": {
        "name": "Footwell light",
        "device_class": "light",
    },
    "drl": {
        "name": "DRL",
        "device_class": "light",
    },
    "hazard": {
        "name": "Hazard lights",
        "device_class": "light",
    },
    "passenger_seatbelt": {
        "name": "Passenger seatbelt",
        "device_class": "safety",
    },
    "turn_signal": {
        "name": "Turn signal",
        "device_class": "light",
    },
    "surround_view_state": {
        "name": "Surround-view state",
        "device_class": "running",
    },
    "wifi_state": {
        "name": "Wi-Fi state",
        "device_class": "connectivity",
    },
    "bluetooth_state": {
        "name": "Bluetooth state",
        "device_class": "connectivity",
    },
    "dashcam_state": {
        "name": "Dashcam state",
        "device_class": "running",
    },
    "wireless_adb_switch": {
        "name": "Wireless ADB switch",
        "device_class": "switch",
    },
    "online": {
        "name": "Online",
        "device_class": "connectivity",
    },
}

# Map from binary sensor key → list of "truthy" string values
# Used by binary_sensor.py _value_to_bool()
BINARY_ON_MAP: dict[str, list[str]] = {'power_state': ['on', 'driving'], 'driver_seatbelt': ['buckled'], 'remote_lock_state': ['locked'], 'charging_state': ['Ready', 'started', 'charging', 'full'], 'left_turn': ['on', 'open'], 'right_turn': ['on', 'open'], 'driver_door_lock': ['locked'], 'passenger_seatbelt_warning': ['alarm'], 'seatbelt_2nd_left': ['buckled'], 'seatbelt_2nd_right': ['buckled'], 'seatbelt_2nd_center': ['buckled'], 'ac_state': ['on', 'open'], 'ac_recirculation': ['recirculation', 'recirc'], 'driver_door': ['open', 'on'], 'passenger_door': ['open', 'on'], 'rear_left_door': ['open', 'on'], 'rear_right_door': ['open', 'on'], 'bonnet': ['open', 'on'], 'trunk': ['open', 'on'], 'fuel_charge_flap': ['open', 'on'], 'auto_hold': ['active'], 'rear_left_approach_warning': ['car approaching', 'alarm'], 'rear_right_approach_warning': ['car approaching', 'alarm'], 'lane_keep_state': ['active1', 'active2'], 'rear_left_door_lock': ['locked'], 'passenger_door_lock': ['locked'], 'rear_right_door_lock': ['locked'], 'trunk_lock': ['locked'], 'rear_left_child_lock': ['locked'], 'rear_right_child_lock': ['locked'], 'sidelights': ['on', 'open'], 'low_beam': ['on', 'open'], 'high_beam': ['on', 'open'], 'front_fog': ['on', 'open'], 'rear_fog': ['on', 'open'], 'footwell_light': ['on', 'open'], 'drl': ['on', 'open'], 'hazard': ['on', 'open'], 'passenger_seatbelt': ['buckled'], 'turn_signal': ['left', 'left2', 'right', 'right2', 'hazard', 'emergency', 'rear flash', 'flash'], 'surround_view_state': ['shown'], 'wifi_state': ['connected'], 'bluetooth_state': ['connected'], 'dashcam_state': ['running'], 'wireless_adb_switch': ['on'], 'online': ['on']}

# Dynamic geofence virtual sensors sent by the Android app.
# Keys look like "geo_<zoneId>" with values "inside"/"outside"; the optional
# companion key "geo_<zoneId>_name" carries the user-defined zone name.
GEOFENCE_KEY_PREFIX = "geo_"
GEOFENCE_NAME_SUFFIX = "_name"
GEOFENCE_ON_VALUES = ["inside"]
